steps:
  - name: hashicorp/terraform:latest
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
        apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        apt-get update && apt-get install terraform -y

  - name: hashicorp/terraform:latest
    args:
      - init

  - name: hashicorp/terraform:latest
    args:
      - validate

  - name: hashicorp/terraform:latest
    args:
      - plan
    env:
      - TF_VAR_project_id=$PROJECT_ID

  - name: hashicorp/terraform:latest
    args:
      - apply
      - '-auto-approve'
    env:
      - TF_VAR_project_id=$PROJECT_ID

# Specify the logs bucket
logsBucket: "gs://my-build-logs-bucket"

substitutions:
  _PROJECT_ID: "infra1-430721"

timeout: "1200s"

serviceAccount: projects/PROJECT_ID/serviceAccounts/SERVICE_ACCOUNT_EMAIL
